compile: Casual.java ContactList.java Contact.java PersonalFriend.java ProfessionalFriend.java Relative.java
	javac Casual.java ContactList.java Contact.java PersonalFriend.java ProfessionalFriend.java Relative.java
	@echo "Compilation completed!\nRun the proogram by typing \
	'java src.ContactList' from parent folder"
clean: 
	rm *.class
